replicaCount: 1

image:
  repository: openwebui/openwebui
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

env:
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: openwebui-secrets
        key: apiKey

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard

ingress:
  enabled: false
